var lang = {
    "tier":"Tier",
    "next_level":"Next Rank",
    "current_level_point":"Points allocated in this tier",
    "skill_points":"Skill Points",
    "book_points":"Tome Points",
    "require":"<p>Requirements:<br />Character Level >= <strong>%d</strong><br />",
    "reach":" rank >= ",
    "skill_level":"",
    "require_prev_level":"Skill points spent in previous tier ",
    "default_char":"Default",
    "reborn_char":"Ascension",
    "player_level":"Character level >=",
    "link":"Link to this build",
    "arden":"Arden",
    "balo":"Balo",
    "jadeon":"Jadeon","modo":"Modo","skysong":"Skysong","lupin":"Lupin","vim":"Vim","rayan":"Rayan","celan":"Celan",
    forta:"Forta",incense:'Incense',
    kytos:'Kytos',psychea:'Psychea',
    hydran:'Hydran',
	seira:'Seira',
	gevrin:'Gevrin',
	sylia:'Sylia',
    chroma:'Chroma level',
    chroma_skills:'Additional skillpoints',
    skill:"Skill",
    select_skill:"select skill",
    descr:"Small description",
    found_error:"Found an error?",
    send:"Send",
    thankyou:"Thank you. To send another bug please click here again",
    writeanerror:"If you are reporting some error in skill, please write down some stats for this skill. At least for your current level. It will help to correct this error much faster."

}
